apiVersion: kuma.io/v1alpha1
kind: RateLimit
mesh: default
metadata:
  name: rate-limit-all-to-backend
spec:
  sources:
    - match:
        kuma.io/service: "*"
  destinations:
    - match:
        kuma.io/service: pricing-api_commerce_svc_80
  conf:
    http:
      requests: 3
      interval: 1m
      onRateLimit:
        status: 429
        headers:
          - key: "x-kuma-rate-limited"
            value: "true"
            append: true
