apiVersion: kuma.io/v1alpha1
kind: TrafficLog
metadata:
  name: all-traffic
mesh: default
spec:
  # This TrafficLog policy applies all traffic in that Mesh.
  sources:
    - match:
        kuma.io/service: "catalog-api_commerce_svc_80"
    - match:
        kuma.io/service: "pricing-api_commerce_svc_80"
    - match:
        kuma.io/service: "products-api_commerce_svc_80"
  destinations:
    - match:
        kuma.io/service: "catalog-api_commerce_svc_80"
    - match:
        kuma.io/service: "pricing-api_commerce_svc_80"
    - match:
        kuma.io/service: "products-api_commerce_svc_80"
  conf:
    backend: logstash
