apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: vault:1.11.3
        volumeMounts:
        - name: config-volume
          mountPath: "/vault/config/server/"
        - name: data-volume
          mountPath: "/vault/data"
        ports:
        - containerPort: 8200
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: VAULT_ADDR
          value: http://127.0.0.1:8200
        args: 
        - "server" 
        - "-config=/vault/config/server/"
        securityContext:
          capabilities:
            add: 
            - IPC_LOCK #vault needs to lock memory
      volumes:
      - name: config-volume
        configMap:
          name: vault-config            
      - name: data-volume
        emptyDir: {}
   
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault
spec:
  selector:
    app: vault
  ports:
    - protocol: TCP
      port: 8200       
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: vault
data:
  serverconfig.hcl: |-
      storage "raft" {
        path    = "/vault/data"
        node_id = "node1"
      }

      listener "tcp" {
        address     = "127.0.0.1:8200"
        tls_disable = "true"
      }

      api_addr = "http://127.0.0.1:8200"
      cluster_addr = "http://127.0.0.1:8201"
      ui = true
      disable_mlock = true  
