apiVersion: v1
kind: Secret
metadata:
  name: external-credential-acl
  namespace: commerce
type: Opaque
data:
  # kongCredType: acl
  kongCredType: YWNs
  group: ZXh0ZXJuYWw=
---
apiVersion: v1
kind: Secret
metadata:
  name: external-credential-canary-acl
  namespace: commerce
type: Opaque
data:
  kongCredType: YWNs
  group: ZXh0ZXJuYWw=
---
apiVersion: v1
kind: Secret
metadata:
  name: marketing-credential-acl
  namespace: commerce
type: Opaque
data:
  # Os dados são armazenados em base64
  # kongCredType: acl
  kongCredType: YWNs
  # key: public-users
  group: bWFya2V0aW5n
---
apiVersion: v1
kind: Secret
metadata:
  name: pricing-credential-acl
  namespace: commerce
type: Opaque
data:
  # Os dados são armazenados em base64
  # kongCredType: acl
  kongCredType: YWNs
  # key: public-users
  group: cHJpY2luZw==
---
apiVersion: v1
kind: Secret
metadata:
  name: external-api-key
  namespace: commerce
type: Opaque
data:
  # Os dados são armazenados em base64
  # kongCredType: key-auth
  kongCredType: a2V5LWF1dGg=
  # key: 
  key: ZXh0ZXJuYWwtYXBpLWtleQ==
---
apiVersion: v1
kind: Secret
metadata:
  name: external-api-canary-key
  namespace: commerce
type: Opaque
data:
  # Os dados são armazenados em base64
  # kongCredType: key-auth
  kongCredType: a2V5LWF1dGg=
  # key: 
  key: ZXh0ZXJuYWwtYXBpLWNhbmFyeS1rZXk=
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: external
  namespace: commerce
  annotations:
    kubernetes.io/ingress.class: kong
username: external
credentials:
- external-api-key
- external-credential-acl
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: external-canary
  namespace: commerce
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: request-transformer-canary
username: external-canary
credentials:
- external-api-canary-key
- external-credential-canary-acl
---
apiVersion: v1
kind: Secret
metadata:
  name: marketing-api-key
  namespace: commerce
type: Opaque
data:
  # Os dados são armazenados em base64
  # kongCredType: key-auth
  kongCredType: a2V5LWF1dGg=
  # key: 
  key: bWFya2V0aW5nLWFwaS1rZXk=
---
apiVersion: v1
kind: Secret
metadata:
  name: pricing-api-key
  namespace: commerce
type: Opaque
data:
  # Os dados são armazenados em base64
  # kongCredType: key-auth
  kongCredType: a2V5LWF1dGg=
  # key: 
  key: cHJpY2luZy1hcGkta2V5


---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: marketing
  namespace: commerce
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: rate-limiting-plugin
username: marketing
credentials:
- marketing-api-key
- marketing-credential-acl

---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: pricing
  namespace: commerce
  annotations:
    kubernetes.io/ingress.class: kong
username: pricing
credentials:
- pricing-api-key
- pricing-credential-acl
---

apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: external-acl
  namespace: commerce
plugin: acl
config:
  allow: ['external']
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: marketing-acl
  namespace: commerce
plugin: acl
config:
  allow: ['marketing']
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: pricing-acl
  namespace: commerce
plugin: acl
config:
  allow: ['pricing']

