apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: global-tcp-log-plugin
  annotations:
    kubernetes.io/ingress.class: kong
  labels:
    global: "true"
config: 
  host: logstash.logstash.svc
  port: 5044
plugin: tcp-log