apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: catalog-cache-plugin
  namespace: commerce
config: 
  response_code:
  - 200
  request_method:
  - GET
  content_type:
  - "application/json; charset=utf-8"
  cache_ttl: 10
  strategy: memory
plugin: proxy-cache
